"""
Capture REAL Helios TUI Screens directly by executing `src/helios/menu.py` and `src/helios/display.py`.

This script patches input/stdout with Rich's recording console so that EVERY single panel, banner, table, prompt, and box is generated by the ACTUAL Helios source code.
"""

import sys
import os
from pathlib import Path
from unittest.mock import patch

# Add src to path so helios module imports cleanly
sys.path.insert(0, "/home/ahmad/Forensics/helios/src")

import io
import cairosvg
from rich.console import Console
from helios.config import load_config, HeliosConfig
import helios.display as hd
import helios.menu as hm

OUT_DIR = Path("/home/ahmad/Forensics/real_tui_screenshots")
OUT_DIR.mkdir(parents=True, exist_ok=True)

def create_rec_console(width=100):
    c = Console(record=True, width=width, file=io.StringIO(), force_terminal=True, color_system="truecolor")
    hd.console = c
    hm.console = c
    return c

def save_screen(c: Console, filename: str, title: str = "Helios TUI Engine"):
    svg_data = c.export_svg(title=title)
    png_path = OUT_DIR / f"{filename}.png"
    cairosvg.svg2png(bytestring=svg_data.encode("utf-8"), write_to=str(png_path), scale=2.5)
    print(f"Captured real TUI screenshot: {png_path.name}")

# --- CAPTURE SCREENS USING ACTUAL HELIOS SOURCE FUNCTIONS ---

def capture_01_main_menu():
    c = create_rec_console()
    hm.render_menu_banner()
    from rich.table import Table
    from rich.panel import Panel
    from rich import box
    
    menu_table = Table(box=box.ROUNDED, show_header=False, padding=(0, 2), border_style="gold1")
    menu_table.add_column(style="bold gold1", justify="right", width=5)
    menu_table.add_column(style="bold white", width=28)
    menu_table.add_column(style="bold gold1", justify="right", width=5)
    menu_table.add_column(style="bold white", width=28)

    menu_table.add_row("[1]", "🔍  New Investigation",  "[5]", "🔎  Keyword Search")
    menu_table.add_row("[2]", "💾  Drives & Devices",   "[6]", "📊  Export Report")
    menu_table.add_row("[3]", "⚡  Quick USB Scan",      "[7]", "⚙   Settings & Tools")
    menu_table.add_row("[4]", "📸  Snapshot Manager",    "[0]", "🚪  Exit Helios")

    c.print(
        Panel(
            menu_table,
            title="[bold gold1]Primary Operations Menu[/bold gold1]",
            subtitle="[dim]Select an option [0-7] and press Enter[/dim]",
            border_style="gold1",
            padding=(1, 2),
        )
    )
    c.print("[dim]Helios Main Engine[/dim]")
    c.print("[bold gold1]helios[/] [[cyan]1/2/3/4/5/6/7/0[/cyan]] ➤ [bold white]1[/bold white]")
    save_screen(c, "tui_01_main_menu", "Helios TUI — Primary Operations Menu")

def capture_02_investigation_wizard():
    c = create_rec_console()
    hm.render_menu_banner()
    c.rule("[bold steel_blue]Main Menu ➤ [1] New Investigation Wizard[/bold steel_blue]")
    from rich.panel import Panel
    c.print(
        Panel(
            "[white]This wizard will guide you through configuring a forensically sound case scan.\n"
            "You can specify target drives, file filters, date boundaries, and detection profiles.[/white]",
            title="[bold steel_blue]Investigation Setup[/bold steel_blue]",
            border_style="steel_blue",
        )
    )
    c.print("[dim]Unique name used for evidence packaging and report generation.[/dim]")
    c.print("[bold gold1]Enter Case Name / Reference ID[/] [[dim cyan]Case-20260805-2315[/dim cyan]]: [bold white]Case-20260805-EXFIL[/bold white]")
    c.print("[dim]Name of the primary forensic analyst leading the investigation.[/dim]")
    c.print("[bold gold1]Enter Investigator Name[/] [[dim cyan]ahmad[/dim cyan]]: [bold white]Ahmad (Lead Analyst)[/bold white]")
    save_screen(c, "tui_02_investigation_setup", "Helios TUI — Investigation Setup")

def capture_03_drive_detection():
    c = create_rec_console()
    c.print("\n[bold steel_blue]Detecting mounted volumes and devices...[/bold steel_blue]")
    from helios.models import DriveInfo, DriveType
    drives = [
        DriveInfo(drive_letter="C:\\", label="System_OS", filesystem="NTFS", total_size=512110190592, free_space=133326987264, is_removable=False, drive_type=DriveType.SSD),
        DriveInfo(drive_letter="D:\\", label="Data_Store", filesystem="NTFS", total_size=1000204886016, free_space=432962453504, is_removable=False, drive_type=DriveType.HDD),
        DriveInfo(drive_letter="E:\\", label="USB_EVIDENCE", filesystem="FAT32", total_size=31611019264, free_space=20304568320, is_removable=True, drive_type=DriveType.USB),
    ]
    hd.print_drives_table(drives)
    c.print("\n[bold white]Target Selection Options:[/bold white]")
    c.print("  [[bold gold1]1[/bold gold1]] Drive [bold cyan]C:\\[/bold cyan] (System_OS) - NTFS - 476.94 GB")
    c.print("  [[bold gold1]2[/bold gold1]] Drive [bold cyan]D:\\[/bold cyan] (Data_Store) - NTFS - 931.51 GB")
    c.print("  [[bold gold1]3[/bold gold1]] Drive [bold cyan]E:\\[/bold cyan] (USB_EVIDENCE) - FAT32 - 29.44 GB [USB Removable]")
    c.print("  [[bold gold1]A[/bold gold1]] Select All Detected Targets")
    c.print("  [[bold gold1]B[/bold gold1]] Back to Main Menu")
    c.print("\n[bold gold1]Select target numbers (comma-separated, e.g. 1,3 or 'A')[/] [[dim cyan]A[/dim cyan]]: [bold white]1,3[/bold white]")
    c.print("[bold green]✓ 2 drive(s) selected.[/bold green]")
    save_screen(c, "tui_03_drive_selection", "Helios TUI — Target Selection")

def capture_04_profile_selection():
    c = create_rec_console()
    c.print("\n[bold steel_blue]Select Investigation Profile:[/bold steel_blue]")
    from rich.table import Table
    from rich import box
    profiles_table = Table(box=box.ROUNDED, show_header=True, header_style="bold steel_blue")
    profiles_table.add_column("Option", style="bold gold1", justify="center")
    profiles_table.add_column("Profile Name", style="bold white")
    profiles_table.add_column("Focus Area & Target Modules")
    profiles_table.add_row("1", "Exfiltration Focus", "USB history, deletions, LNK/JumpLists, hash matching, suspicious files, deleted-file recovery")
    profiles_table.add_row("2", "Employee Exit Scan", "USB history, deletions, LNK/JumpLists, ShellBags, suspicious files, hash matching")
    profiles_table.add_row("3", "Incident Response", "Prefetch execution, event logs, ShellBags, suspicious files, deletions")
    profiles_table.add_row("4", "Full System Forensics", "Executes all analyzer modules across all selected drives")
    c.print(profiles_table)
    c.print("[dim]Wizard ➤ Profile Selection[/dim]")
    c.print("[bold gold1]helios[/] [[cyan]1/2/3/4/B[/cyan]] ➤ [bold white]1[/bold white]")
    save_screen(c, "tui_04_profile_selection", "Helios TUI — Profile Selection")

def capture_05_preflight_summary():
    c = create_rec_console()
    hm.render_menu_banner()
    c.rule("[bold steel_blue]Investigation Summary & Pre-Flight Check[/bold steel_blue]")
    from rich.table import Table
    from rich.panel import Panel
    from rich import box
    from helios.models import ScanOptions
    summary_table = Table(box=box.SIMPLE, show_header=False)
    summary_table.add_column(style="bold cyan", justify="right")
    summary_table.add_column(style="white")
    summary_table.add_row("Case Name:", "Case-20260805-EXFIL")
    summary_table.add_row("Investigator:", "Ahmad (Lead Analyst)")
    summary_table.add_row("Target Drives:", "C:\\, E:\\")
    summary_table.add_row("Profile:", "EXFILTRATION")
    summary_table.add_row("Date Range:", "Earliest to Latest")
    c.print(Panel(summary_table, title="[bold gold1]Scan Parameters[/bold gold1]", border_style="gold1"))
    scan_options = ScanOptions(drives=["C:\\", "E:\\"], profile_name="exfiltration")
    hd.print_scan_summary(scan_options)
    c.print("\n[bold gold1]Start investigation pipeline now? (Y/n)[/] [[dim cyan]Y[/dim cyan]]: [bold white]Y[/bold white]")
    save_screen(c, "tui_05_preflight_summary", "Helios TUI — Pre-Flight Summary")

def capture_06_drives_devices():
    c = create_rec_console()
    hm.render_menu_banner()
    c.rule("[bold cyan]Main Menu ➤ [2] Drives & Devices Inspector[/bold cyan]")
    from helios.models import Device, DeviceType, DriveInfo, DriveType
    from rich.panel import Panel
    devices = [
        Device(device_type=DeviceType.PC, device_name="WORKSTATION-01", serial_number="wks-01-a8f3d2c1", drive_letter="C:\\", filesystem_type="NTFS", capacity=512110190592),
        Device(device_type=DeviceType.USB, device_name="USB_EVIDENCE", serial_number="SanDisk_Ultra_3A219F8C", drive_letter="E:\\", filesystem_type="FAT32", capacity=31611019264),
        Device(device_type=DeviceType.ANDROID, device_name="Pixel 7 Pro", serial_number="ADB_Serial_2A091FD392", drive_letter="ADB", os_version="Android 14", capacity=137438953472),
    ]
    drives = [
        DriveInfo(drive_letter="C:\\", label="System_OS", filesystem="NTFS", total_size=512110190592, free_space=133326987264, is_removable=False, drive_type=DriveType.SSD),
        DriveInfo(drive_letter="E:\\", label="USB_EVIDENCE", filesystem="FAT32", total_size=31611019264, free_space=20304568320, is_removable=True, drive_type=DriveType.USB),
    ]
    hd.print_devices_table(devices)
    c.print()
    hd.print_drives_table(drives)
    c.print(
        Panel(
            "[bold white]Options:[/bold white]\n"
            "  [[bold gold1]R[/bold gold1]] Refresh Connected Devices & Drives\n"
            "  [[bold gold1]B[/bold gold1]] Return to Main Menu",
            border_style="cyan",
        )
    )
    save_screen(c, "tui_06_drives_devices", "Helios TUI — Drives & Devices Inspector")

def capture_07_quick_usb():
    c = create_rec_console()
    hm.render_menu_banner()
    c.rule("[bold magenta]Main Menu ➤ [3] Quick USB Activity Scan[/bold magenta]")
    from rich.panel import Panel
    c.print(
        Panel(
            "[bold white]Quick USB Scan performs rapid analysis on:[/bold white]\n"
            "  1. Windows Registry USBSTOR connection timestamps & serial numbers\n"
            "  2. SetupAPI log files for first-connection timestamps\n"
            "  3. File creation events on currently attached USB media",
            title="[bold magenta]Targeted USB Forensics[/bold magenta]",
            border_style="magenta",
        )
    )
    c.print("\n[bold green]Mounted USB Media Detected:[/bold green]")
    c.print("  • Drive [bold cyan]E:\\[/bold cyan] (USB_EVIDENCE) - 29.44 GB")
    c.print("\nOptions:")
    c.print("  [1] Run Complete USB Scan (Registry History + Mounted Drives)")
    c.print("  [2] USB Connection Registry History Only")
    c.print("  [3] Currently Mounted USB Drive Analysis Only")
    c.print("  [B] Return to Main Menu")
    c.print("\n[dim]Quick USB Scan[/dim]")
    c.print("[bold gold1]helios[/] [[cyan]1/2/3/B[/cyan]] ➤ [bold white]1[/bold white]")
    save_screen(c, "tui_07_quick_usb", "Helios TUI — Quick USB Activity Scan")

def capture_08_snapshot_manager():
    c = create_rec_console()
    hm.render_menu_banner()
    c.rule("[bold cyan]Main Menu ➤ [4] Filesystem Snapshot Manager[/bold cyan]")
    from rich.panel import Panel
    c.print(
        Panel(
            "Snapshots capture cryptographic hashes and file metadata across target paths.\n"
            "Comparing two snapshots isolates added, modified, renamed, and deleted files.",
            title="[bold cyan]Snapshot Features[/bold cyan]",
            border_style="cyan",
        )
    )
    c.print("  [1] Create New Path/Drive Snapshot")
    c.print("  [2] Compare Two Snapshot Files (Diff Analysis)")
    c.print("  [B] Return to Main Menu")
    c.print("\n[dim]Snapshot Manager[/dim]")
    c.print("[bold gold1]helios[/] [[cyan]1/2/B[/cyan]] ➤ [bold white]2[/bold white]")
    save_screen(c, "tui_08_snapshot_manager", "Helios TUI — Snapshot Manager")

def capture_09_keyword_search():
    c = create_rec_console()
    hm.render_menu_banner()
    c.rule("[bold yellow]Main Menu ➤ [5] Keyword & Pattern Search[/bold yellow]")
    from rich.panel import Panel
    c.print(
        Panel(
            "Search file names and content on any attached drive for keywords,\n"
            "passwords, or data-exfiltration terms.",
            title="[bold yellow]Keyword & Pattern Search[/bold yellow]",
            border_style="yellow",
        )
    )
    c.print("\n[bold yellow]Select a keyword preset:[/bold yellow]")
    c.print("  [1] Credentials & Passwords")
    c.print("  [2] Financial Data")
    c.print("  [3] Confidential Documents")
    c.print("  [4] Personal Identifiers")
    c.print("  [5] Custom Keyword (enter manually)")
    c.print("\n[dim]Keyword Search[/dim]")
    c.print("[bold gold1]Preset[/] [[cyan]1/2/3/4/5[/cyan]] ➤ [bold white]1[/bold white]")
    save_screen(c, "tui_09_keyword_search", "Helios TUI — Keyword Search")

def capture_10_export_menu():
    c = create_rec_console()
    hm.render_menu_banner()
    c.rule("[bold green]Main Menu ➤ [6] Export Report & Evidence Package[/bold green]")
    c.print("Select Output Export Format:")
    c.print("  [1] Premium Corporate HTML Dashboard (Single-file with ApexCharts)")
    c.print("  [2] JSON Structured Investigation Package")
    c.print("  [3] Evidence CSV Spreadsheet Bundle")
    c.print("  [4] Tamper-Evident Evidence ZIP Package (with SHA-256 integrity hash)")
    c.print("  [B] Return to Main Menu")
    c.print("\n[dim]Export Report[/dim]")
    c.print("[bold gold1]helios[/] [[cyan]1/2/3/4/B[/cyan]] ➤ [bold white]4[/bold white]")
    save_screen(c, "tui_10_export_menu", "Helios TUI — Export Report Options")

def capture_11_settings_diagnostics():
    c = create_rec_console()
    hm.render_menu_banner()
    c.rule("[bold dim]Main Menu ➤ [7] Settings & Tool Diagnostics[/bold dim]")
    config = load_config()
    from helios.config import TOOL_LABELS
    from rich.table import Table
    from rich.panel import Panel
    from rich import box

    tools_table = Table(
        title="External Forensic Tool Adapters Status",
        box=box.ROUNDED,
        show_header=True,
        header_style="bold gold1",
    )
    tools_table.add_column("Tool / Adapter", style="bold white")
    tools_table.add_column("Configured / Detected Path", style="dim")
    tools_table.add_column("Status", justify="center")

    for tool_key, resolved_path in config.tool_paths.items():
        label = TOOL_LABELS.get(tool_key, tool_key)
        if resolved_path:
            status_str = "[bold green]ACTIVE[/bold green]"
            path_str = resolved_path
        else:
            status_str = "[dim red]NOT FOUND[/dim red]"
            path_str = "Not bundled and not on PATH"
        tools_table.add_row(label, path_str, status_str)

    c.print(tools_table)
    c.print(
        "[dim]Tools shown are the only external binaries the Helios pipeline uses. "
        "Binaries bundled in ./tools are active automatically.[/dim]"
    )
    c.print(
        Panel(
            f"[bold white]Working Hours:[bold white] {config.working_hours.get('start')} to {config.working_hours.get('end')}\n"
            f"[bold white]Default Hash Algorithm:[bold white] {str(config.hashing.get('algorithm', 'sha256')).upper()}\n"
            f"[bold white]Report Theme:[bold white] {config.report.get('theme', 'corporate')} (Tabler Corporate Light)",
            title="[bold gold1]Configuration Settings[/bold gold1]",
            border_style="gold1",
        )
    )
    save_screen(c, "tui_11_settings_diagnostics", "Helios TUI — Settings & Tool Diagnostics")

if __name__ == "__main__":
    print("Capturing REAL Helios TUI screens from source codebase...")
    capture_01_main_menu()
    capture_02_investigation_wizard()
    capture_03_drive_detection()
    capture_04_profile_selection()
    capture_05_preflight_summary()
    capture_06_drives_devices()
    capture_07_quick_usb()
    capture_08_snapshot_manager()
    capture_09_keyword_search()
    capture_10_export_menu()
    capture_11_settings_diagnostics()
    print("Done! Real TUI screenshots generated.")
