import csv
import logging
import subprocess
import time
from pathlib import Path
from typing import Any

from helios.adapters.base import ForensicToolAdapter, ToolRunResult, resolve_tool_binary
from helios.models import DataEvent, EventType

logger = logging.getLogger(__name__)

# Deduplicates repeated "No CSV files found" warnings across per-file runs.
_logged_csv_warnings: set[str] = set()


class EZToolsAdapter(ForensicToolAdapter):
    """
    Adapter for Eric Zimmerman's Forensic Tools Suite.
    Provides interfaces to execute and parse output from LECmd, JLECmd, SBECmd, PECmd, and RBCmd.
    """

    def __init__(self, config_dir: Path | None = None, config: dict | None = None, tool_path: str | None = None):
        """
        Initialize the EZToolsAdapter.

        Args:
            config_dir: Optional path to a directory containing the EZ tools executables.
            config: Optional configuration dictionary.
            tool_path: Optional path to primary executable.
        """
        super().__init__(config=config or {}, tool_path=tool_path)
        self.config_dir = config_dir
        self.tools = {
            "lecmd": "LECmd.exe",
            "jlecmd": "JLECmd.exe",
            "sbecmd": "SBECmd.exe",
            "pecmd": "PECmd.exe",
            "rbcmd": "RBCmd.exe",
        }

    def tool_name(self) -> str:
        """Returns the name of the tool adapter."""
        return "Eric Zimmerman Tools Adapter"

    def is_available(self) -> bool:
        """
        Check if the required EZ tools are available in the PATH or config directory.
        At least one tool must be available for this adapter to be considered available.

        Returns:
            True if at least one EZ tool is found, False otherwise.
        """
        for tool in self.tools:
            if self._get_tool_path(tool) is not None:
                return True
        return False

    def run(self, args: list[str], timeout: int = 300) -> ToolRunResult:
        """Run EZTool command with specified arguments list."""
        tool_name = args[0] if args else "lecmd"
        exe = self._get_tool_path(tool_name)
        cmd = [str(exe or tool_name)] + args[1:]
        return self.run_subprocess(cmd, timeout=timeout)

    def parse_output(self, raw_output: str) -> list[DataEvent]:
        """Parse raw text output into DataEvent objects.

        Events are only produced for lines containing a parseable timestamp;
        raw lines without one are skipped to avoid fabricating evidence.
        """
        from helios.adapters.base import extract_timestamp

        events = []
        for line in raw_output.splitlines():
            line = line.strip()
            if not line:
                continue
            timestamp = extract_timestamp(line)
            if timestamp is None:
                continue
            events.append(DataEvent(
                timestamp=timestamp,
                event_type=EventType.APP_EXECUTE,
                source_device="UNKNOWN",
                source_path=line,
                raw_source="EZTools",
                metadata={"raw_line": line}
            ))
        return events

    def tool_available(self, tool_name: str) -> bool:
        """
        Check whether one specific EZ tool (e.g. 'lecmd', 'sbecmd') can be
        resolved on this platform. Analyzers use this to fail loudly —
        with an actionable message — instead of silently returning zero
        events when only the Windows .exe build is present.
        """
        return self._get_tool_path(tool_name) is not None

    def _get_tool_path(self, tool_name: str) -> Path | None:
        """
        Helper to find the executable path for a specific tool.

        Args:
            tool_name: The internal name of the tool (e.g., 'lecmd').

        Returns:
            The Path to the executable if found, otherwise None.
        """
        executable = self.tools.get(tool_name)
        if not executable:
            return None

        explicit = str(self.config_dir / executable) if self.config_dir else None
        return resolve_tool_binary(executable.replace(".exe", ""), explicit_path=explicit)

    def _run_cmd_and_parse_csv(
        self, cmd: list[str], output_csv_dir: Path, expected_csv_prefix: str
    ) -> list[dict[str, Any]]:
        """
        Run a command and parse the resulting CSV output.

        Args:
            cmd: The command to execute as a list of strings.
            output_csv_dir: The directory where the tool is expected to write its CSV output.
            expected_csv_prefix: The prefix of the CSV file generated by the tool.

        Returns:
            A list of dictionaries representing the rows in the CSV file.
        """
        logger.debug(f"Executing command: {' '.join(cmd)}")
        start_time = time.time()
        timed_out = False
        try:
            # Ensure the output directory exists
            output_csv_dir.mkdir(parents=True, exist_ok=True)

            result = self.run_subprocess(cmd, timeout=120)
            timed_out = result.returncode < 0

            if result.returncode != 0 and not timed_out:
                # Zimmerman tools routinely exit non-zero on PARTIAL success
                # (SBECmd skips corrupt hives, PECmd skips corrupt .pf files,
                # several builds return warning codes). A complete-or-partial
                # fresh CSV is still evidence — parse it, but say so loudly.
                logger.warning(
                    "Command exited %d; attempting to parse any freshly written "
                    "CSV anyway (partial success). Stderr: %s",
                    result.returncode, result.stderr[:500],
                )

        except subprocess.TimeoutExpired:
            logger.error(f"Command timed out after 120s: {cmd}")
            return []
        except Exception as e:
            logger.error(f"Error executing command {' '.join(cmd)}: {e}")
            return []

        try:
            candidates = list(output_csv_dir.glob("*.csv"))
            if not candidates:
                logger.debug(f"No CSV files found in {output_csv_dir}")
                return []

            # Only CSVs written during THIS run count (5s clock-skew tolerance).
            # This is THE stale-ingestion guard — evidence is never sourced
            # from leftover files of earlier runs, whatever the exit code.
            fresh_csvs = [p for p in candidates if p.stat().st_mtime >= start_time - 5.0]
            if not fresh_csvs:
                logger.warning(
                    "No freshly written CSV output in %s — refusing to ingest "
                    "pre-existing files as evidence.", output_csv_dir,
                )
                return []

            latest_csv = max(fresh_csvs, key=lambda p: p.stat().st_mtime)
            return self._parse_csv(latest_csv)

        except Exception as e:
            logger.error(f"Error parsing CSV output in {output_csv_dir}: {e}")
            return []

    def _parse_csv(self, csv_path: Path) -> list[dict[str, Any]]:
        """
        Read a CSV file and convert it to a list of dictionaries.

        Args:
            csv_path: The path to the CSV file.

        Returns:
            List of dictionaries representing the CSV rows.
        """
        results = []
        try:
            with open(csv_path, mode="r", encoding="utf-8-sig") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    # Clean up keys and values if necessary
                    clean_row = {k.strip(): (v.strip() if v is not None else "") for k, v in row.items() if k}
                    results.append(clean_row)
        except Exception as e:
            logger.error(f"Failed to read CSV file at {csv_path}: {e}")
            
        return results

    def run_lecmd(self, lnk_path: Path, output_csv_dir: Path) -> list[dict[str, Any]]:
        """
        Parse LNK files using LECmd.exe.

        Args:
            lnk_path: Path to a single .lnk file or a directory containing .lnk files.
            output_csv_dir: Directory where the CSV output should be saved.

        Returns:
            List of parsed LNK file records.
        """
        tool_path = self._get_tool_path("lecmd")
        if not tool_path:
            logger.error("LECmd not found. Ensure it is installed and in PATH/config.")
            return []

        # Construct the command
        # Use -d for directory, -f for file
        flag = "-d" if lnk_path.is_dir() else "-f"
        cmd = [str(tool_path), flag, str(lnk_path), "--csv", str(output_csv_dir), "-q"]
        
        # Expected CSV prefix for LECmd
        # Usually format is: LECmd_Output_yyyy-MM-ddHHmmss.csv
        # We will look for "LECmd"
        return self._run_cmd_and_parse_csv(cmd, output_csv_dir, "LECmd")

    def run_jlecmd(self, jumplist_path: Path, output_csv_dir: Path) -> list[dict[str, Any]]:
        """
        Parse Automatic/CustomDestinations JumpLists using JLECmd.exe.

        Args:
            jumplist_path: Path to a single JumpList file or a directory containing them.
            output_csv_dir: Directory where the CSV output should be saved.

        Returns:
            List of parsed JumpList records.
        """
        tool_path = self._get_tool_path("jlecmd")
        if not tool_path:
            logger.error("JLECmd not found.")
            return []

        flag = "-d" if jumplist_path.is_dir() else "-f"
        cmd = [str(tool_path), flag, str(jumplist_path), "--csv", str(output_csv_dir), "-q"]
        
        return self._run_cmd_and_parse_csv(cmd, output_csv_dir, "JLECmd")

    def run_sbecmd(self, registry_hive: Path, output_csv_dir: Path) -> list[dict[str, Any]]:
        """
        Parse ShellBags using SBECmd.exe.

        Args:
            registry_hive: Path to a single registry hive or directory containing hives.
                           (NTUSER.DAT, UsrClass.dat)
            output_csv_dir: Directory where the CSV output should be saved.

        Returns:
            List of parsed ShellBags records.
        """
        tool_path = self._get_tool_path("sbecmd")
        if not tool_path:
            logger.error("SBECmd not found.")
            return []

        flag = "-d" if registry_hive.is_dir() else "-f"
        cmd = [str(tool_path), flag, str(registry_hive), "--csv", str(output_csv_dir), "-q"]
        
        return self._run_cmd_and_parse_csv(cmd, output_csv_dir, "SBECmd")

    def run_pecmd(self, prefetch_path: Path, output_csv_dir: Path) -> list[dict[str, Any]]:
        """
        Parse Prefetch files using PECmd.exe.

        Args:
            prefetch_path: Path to a single .pf file or a directory of .pf files.
            output_csv_dir: Directory where the CSV output should be saved.

        Returns:
            List of parsed Prefetch records.
        """
        tool_path = self._get_tool_path("pecmd")
        if not tool_path:
            logger.error("PECmd not found.")
            return []

        flag = "-d" if prefetch_path.is_dir() else "-f"
        cmd = [str(tool_path), flag, str(prefetch_path), "--csv", str(output_csv_dir), "-q"]
        
        return self._run_cmd_and_parse_csv(cmd, output_csv_dir, "PECmd")

    def run_rbcmd(self, recycle_bin_dir: Path, output_csv_dir: Path) -> list[dict[str, Any]]:
        """
        Parse Recycle Bin $I files using RBCmd.exe.

        Args:
            recycle_bin_dir: Path to the Recycle Bin directory (containing $I files) or a single file.
            output_csv_dir: Directory where the CSV output should be saved.

        Returns:
            List of parsed Recycle Bin records.
        """
        tool_path = self._get_tool_path("rbcmd")
        if not tool_path:
            logger.error("RBCmd not found.")
            return []

        flag = "-d" if recycle_bin_dir.is_dir() else "-f"
        cmd = [str(tool_path), flag, str(recycle_bin_dir), "--csv", str(output_csv_dir), "-q"]
        
        return self._run_cmd_and_parse_csv(cmd, output_csv_dir, "RBCmd")
